import type { NextPage } from "next";
import Head from "next/head";

export const HeadPart: NextPage = () => {
  return (
    <Head>
      <title>Brainstorm App</title>
      <meta
        name="This app uses next.js dynamic import"
        content="Generated by create next app with react mouse particles"
      />
      <link rel="icon" href="favicons/favicon.ico" />
    </Head>
  );
};
